### ISSUE TITLE
Child collection validator being instantiated automatically in .net core 2

### ISSUE THREAD

**Issue by lokirangers** [JeremySkinner/FluentValidation#651]
We have just upgraded our solution from .net core 1, with FluentValidation 6.4.0 to .net core 2, with the latest version of FluentValidation, and when testing our REST api I got an error about being unable to activate an instance of one of my validators when doing a PUT to one of my controllers.

The model being sent is defined as follows:

```
 public class AppFunctionParamValuesModel
    {
        public int AppFunctionID { get; set; }
        public List<AppFunctionParamValueModel> ParamValues { get; set; }
    }

    public class AppFunctionParamValueModel
    {
        public string Code { get; set; }
        public Boolean UserLevel { get; set; }
        public Boolean? AllowAtUserLevel { get; set; }
        public string Value { get; set; }

        public DateTime? UpdatedDate { get; set; }
    }
```

There is a validator defined for the parent model, the pertinent details of as follows:

```
public class AppFunctionParamValuesValidator: AbstractValidator<AppFunctionParamValuesModel>
    {
        private readonly IHttpContextAccessor _accessor;
        private readonly IProviderFactory _providerfactory;
        private readonly IValidatorFactory _validatorfactory;
        private readonly IErrorService _errorservice;

        public AppFunctionParamValuesValidator(IHttpContextAccessor accessor, IProviderFactory providerfactory, IValidatorFactory validatorfactory,
                                IErrorService errorservice)
        {
            _accessor = accessor;
            _providerfactory = providerfactory;
            _validatorfactory = validatorfactory;
            _errorservice = errorservice;

            RuleFor(x => x.AppFunctionID).Must(AppFunctionIDValid).WithMessage(x => GetErrorMessage(x, "INVALIDKEY", "AppFunctionParamValues", "AppFunctionID", x.AppFunctionID.ToString()));
            RuleFor(x => x.ParamValues)
               .SetCollectionValidator(x => new AppFunctionParamValueValidator(_accessor, _providerfactory, _errorservice, x));

        }
        // rule method removed for clarity
    }
```

And a validator for the child model, similarly partially shown as follows:

```
public class AppFunctionParamValueValidator: TranSendValidator<AppFunctionParamValueModel>
    {
        private readonly IHttpContextAccessor _accessor;
        private readonly IProviderFactory _providerfactory;
        private readonly IErrorService _errorservice;
        private AppFunctionParamValuesModel _parent;

        public AppFunctionParamValueValidator(IHttpContextAccessor accessor, IProviderFactory providerfactory,
                                IErrorService errorservice, AppFunctionParamValuesModel parent)
        {
            _accessor = accessor;
            _providerfactory = providerfactory;
            _errorservice = errorservice;
            _parent = parent;

            RuleFor(x => x.Code).Must(ParamCodeValid).WithMessage(x => GetErrorMessage(x, "INVALIDFK", "Code"));
            RuleFor(x => x.UserLevel).Must(CompanyLevelValid).WithMessage(x => GetErrorMessage(x, "APPFUNCPARAM001"));
            RuleFor(x => x.UserLevel).Must(UserLevelValid).WithMessage(x => GetErrorMessage(x, "APPFUNCPARAM002"));
            RuleFor(x => x.AllowAtUserLevel).Must(AllowAtUserLevelValid).WithMessage(x => GetErrorMessage(x, "APPFUNCPARAM003"));
            RuleFor(x => x.Value).Must(ValueValid).WithMessage(x => GetErrorMessage(x, "APPFUNCPARAM004"));
            RuleFor(x => x.UpdatedDate).Must(NotBeStale).WithMessage(ApiError.CONCURRENCY_FAILURE);
        }

    // rule methods removed for clarity
}
```

in our .net core 1 project, the above worked fine, with the SetCollectionValidator creating the instance of the validator for each child model, passing the parent instance into it so it had it available when validating the child, as each child entry needs access to the full parent record from our database in order to validate.

In .net core 2, the above generates the following exception:

InvalidOperationException: Unable to resolve service for type 'Models.AppFunctionParamValuesModel' while attempting to activate 'Validation.AppFunctionParamValueValidator'.

Given that the above error is generally displayed when something cannot be activated by the dependency injection mechanism this looked odd, as I'm not trying to activate the validator via DI, I am calling the constructor manually, passing in the relevant parameters.  The parent being passed clearly cannot be resolved via DI but this should not be an issue as I'm not using DI.

To prove that it appears to be using DI somewhere to create an instance of the child validator I commented out the lines in my parent validator defining the collection validator, and the error still occurred.  If I add a constructor to my child validator that does not have the parent being passed, such that all constructor parameters can be resolved via DI I can see under debug that it creates an instance of the child validator using this new constructor for each child value contained in the list of children in the model being sent via postman.  I can also see under debug that these child validator instances are being created before the validator instance for the parent object, as if something is walking the object tree down and creating the instances from bottom up.

Reading the documentation it says that child validation is switched off by default, I even tried explicitly setting ImplicitlyValidateChildProperties = false in my Startup.cs, which didnt seem to have any effect.

The validators **are** both registered with DI, as call the RegisterValidatorsFromAssemblyContaining<Startup>() method within Startup.cs but as the child model isnt being received directly into the controller my understanding was that no child validation would take place unless explicitly called by the parent.

If I leave this dummy constructor in, with no rules in it, the validation appears to work as before, however it is still creating additional, empty, instances that I don't really want, and which I'm not 100% sure aren't going to cause any issues further down the line.

I'm hoping you can tell me if I'm doing something wrong, or if there is a .net core 2 setup task that I've missed, or if this is a bug that needs looking at.

Thanks.

**Comment by JeremySkinner** [comment]
If `ImplicitlyValidateChildProperties` is set to false then it shouldn't attempt to create child validators as part of the standard validation process. 

Please could you post the full stack trace so I can see where abouts the validator is being instantiated?

**Comment by lokirangers** [comment]
Stack trace as follows:

`System.InvalidOperationException: Unable to resolve service for type 'TranSend.Web.Models.AppFunctionParamValuesModel' while attempting to activate 'TranSend.Web.Validation.AppFunctionParamValueValidator'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
   at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at FluentValidation.AspNetCore.ServiceProviderValidatorFactory.CreateInstance(Type validatorType)
   at FluentValidation.ValidatorFactoryBase.GetValidator(Type type)
   at FluentValidation.AspNetCore.FluentValidationModelValidator.Validate(ModelValidationContext mvContext)
   at FluentValidation.AspNetCore.ValidationVisitorFork.ValidateNode()
   at FluentValidation.AspNetCore.ValidationVisitorFork.VisitComplexType(IValidationStrategy defaultStrategy)
   at FluentValidation.AspNetCore.ValidationVisitorFork.Visit(ModelMetadata metadata, String key, Object model)
   at FluentValidation.AspNetCore.ValidationVisitorFork.VisitChildren(IValidationStrategy strategy)
   at FluentValidation.AspNetCore.ValidationVisitorFork.VisitComplexType(IValidationStrategy defaultStrategy)
   at FluentValidation.AspNetCore.ValidationVisitorFork.Visit(ModelMetadata metadata, String key, Object model)
   at FluentValidation.AspNetCore.ValidationVisitorFork.VisitChildren(IValidationStrategy strategy)
   at FluentValidation.AspNetCore.ValidationVisitorFork.VisitComplexType(IValidationStrategy defaultStrategy)
   at FluentValidation.AspNetCore.ValidationVisitorFork.Visit(ModelMetadata metadata, String key, Object model)
   at FluentValidation.AspNetCore.ValidationVisitorFork.Validate(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel)
   at FluentValidation.AspNetCore.FluentValidationObjectModelValidator.Validate(ActionContext actionContext, ValidationStateDictionary validationState, String prefix, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.<BindModelAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()`

**Comment by JeremySkinner** [comment]
I can't reproduce it - in my tests the child isn't instantiated. Could you put together a small sample project that reproduces the issue? I'll then be able to look further.

Thanks

**Comment by lokirangers** [comment]
I shall have a go. :-)

**Comment by lokirangers** [comment]
ok, cutdown project attached.

Using postman and posting to the following url: https://localhost:44388/api/Test

I post the following json object:

```
{
	"AppFunctionID": 7,
	"paramValues": [
		{
			"code": "C2",
			"userLevel": false,
			"allowAtUserLevel": true,
			"value": "ref"
		},
		{
			"code": "C5",
			"userLevel": true,
			"value": "true"
		}
		]
}
```

As it stands the solution generates the exception, but you can see from the code in the AppFunctionParamValuesValidator class that the SetCollectionValidator is currently commented out.

If you uncomment out the second constructor in the AppFunctionParamValueValidator class, the POST will work and if you put breakpoints in you can see that 2 instances of this validator are being created before it creates the parent AppFunctionParamValuesValidator.



[cutdown_project.zip](https://github.com/JeremySkinner/FluentValidation/files/1579483/cutdown_project.zip)

**Comment by JeremySkinner** [comment]
At the moment it looks like a bug in aspnetcore. Usually for child properties they send MetadataKind = Property, and MetadataKind = Type for root-level objects. However for child *collections* they are also sending across MetadataKind = Type, so FluentValidation has no way of differentiating this from a root-level object. I'll see if I can find a workaround.

**Comment by JeremySkinner** [comment]
I believe I have a fix - I'll push an update to nuget in a few minutes.

**Comment by JeremySkinner** [comment]
I've pushed out 7.3.2 with a fix - could you update and give it a try?

**Comment by lokirangers** [comment]
Thanks, I'll give it a go later today

**Comment by lokirangers** [comment]
Hi, I'm afraid that my main application, and that cutdown one I uploaded, still throws the exception if I only have the constructor that requires a non-DI supplied parameter.

**Comment by JeremySkinner** [comment]
Are you definitely running 7.3.2? I tested it with the sample application that you sent me and it worked correctly without any exceptions.

**Comment by JeremySkinner** [comment]
Hm I just tried it again and the binaries on nuget seem to be giving the same error....perhaps there was a problem publishing. I'll try and take another look today.

**Comment by JeremySkinner** [comment]
I'm not sure what happened there....I'm convinced that my change yesterday had fixed it but apparently not. I've just pushed out 7.3.3 which looks more promising - could you give it a try?

**Comment by lokirangers** [comment]
I installed and tried 7.3.4 today which seems to have resolved my issue, thanks!
